apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: url-shortener
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc:4317"
